### ISSUE TITLE
Docs need more detail on how to resolve and use ethr DIDs

### ISSUE THREAD

**Issue by alexander-morris** [uport-project/ethr-did-resolver#25]
We're working on a php library to match this functionality and it would help a lot to have a bit more information about how to retrieve the full document for a given DID

**Comment by mirceanis** [comment]
The gist is that the document is not retrieved from somewhere, it is constructed based on information gathered from the registry smart contract.
More specifically, the document is built based on the result of the `identityOwner(identity)` method call, and from the list of events emitted by the registry contract concerning that identity.
Each event contains a `previousChange` field you can use to build the complete list of events for an identity.
Then, each event in that history can contain information needed to build the `publicKey`, `authentication `, or `service` arrays in the resulting DID Document.

Is there something specific in the documentation that is confusing?

**Comment by vasa-develop** [comment]
@alexander-morris  If this is of any help, [**here is a working example**](https://github.com/cluster-labs/did-ethr-demo) of `did-ethr` used by uport

**Comment by Namenox** [comment]
@mirceanis thanks for your support. Mainly what is confusing is that everything that is well documented is outdated, or at least there is not a global set of diagrams explaining the flow correctly for noobs, like myself.

For example, the basic functionality for building anything that is verifiable is the ability to check signatures. In order to check signatures, it is needed a public key. According to the specs, this is the flow to get the key:

(From https://github.com/uport-project/specs/blob/develop/pki/index.md)
![jwtflow](https://user-images.githubusercontent.com/34040174/62848071-01c39c80-bcda-11e9-8f67-9c07dcb81f21.png)

From the documentation of this library and your comment, it seems this is no longer true, but rather the did doc is constructed from events queried to the registry.

Funny enough, the only noob solution working is from @vasa-develop , which I truly appreiciate. However, after getting the did doc STILL i'm not able to get a public key, getting this DDO:

Ethr DID Document


{
  '@context': 'https://w3id.org/did/v1',
  id: 'did:ethr:0xe4e73272b77cab09b65b651836cd8ec4ada08715',
  publicKey: [
    {
      id: 'did:ethr:0xe4e73272b77cab09b65b651836cd8ec4ada08715#owner',
      type: 'Secp256k1VerificationKey2018',
      owner: 'did:ethr:0xe4e73272b77cab09b65b651836cd8ec4ada08715',
      ethereumAddress: '0xe4e73272b77cab09b65b651836cd8ec4ada08715'
    }
  ],
  authentication: [
    {
      type: 'Secp256k1SignatureAuthentication2018',
      publicKey: 'did:ethr:0xe4e73272b77cab09b65b651836cd8ec4ada08715#owner'
    }
  ]
}


Maybe I'm wrong and there is no need of a "public key" as I understand it, so I checked online if it was possible to get a public key from an ethereum address. Apparently, it is possible via this method 
[](https://ethereum.stackexchange.com/questions/13778/get-public-key-of-any-ethereum-account)

only if there has been a transaction from that account.


Again, sorry if I'm mistaken but the documentation is confusing. We need a simple way of obtaining a public key, or otherwise, a clear example of how to do it. Ty

**Comment by mirceanis** [comment]
@Namenox getting a public key from an ethereum address should be impossible since the address is part of the hash of the public key.

What happens during verification is that the public key is recovered from the `data`+`signature` using a method usually called `ecRecover` and then an `ethereumAddress` is derived from that. If the address matches the `ethereumAddress` of one DID document then it is considered a match.

Note that for this to work directly, a "recovery byte" is needed as part of the signature (making the signature 65 bytes long instead of 64). 
In case that byte is not present, one would have to check both possible values (either `0` or `1`), and match the DID Document against 2 possible `ethereumAddress`es.

Also note that many libraries that provide an `ecRecover` method may expect the recovery byte values to be `27` & `28` instead of `0` & `1`

**Comment by Namenox** [comment]
@mirceanis thank you very much, this answer was great for understanding. 

This may not be the right place to ask this, so please fell free to move it somewhere:

-How is uPort solution dealing with privacy? Are the users expected to create a new DID for every service they interact with? (Or will it be added as a feature in the future?) Please note that i'm not stating that this should be the way to go, but I think I read it somewhere on uPort's medium and I would like to make use of this oportunity to clarify things.

- What's uPort business model?

**Comment by mirceanis** [comment]
In the existing solution (the uPort mobile app), a single root-DID is used for receiving and sharing verifiable credentials (off-chain).
The off-chain verifiable credential data is only available to the user's device and to the parties the user decides to share with (during a selective disclosure).
It's technically possible to use different DIDs for off-chain interactions but because of the relatively small privacy attack surface it is not enabled in the app.

That being said, for ETH transactions the situation is different since on-chain interactions are public. The app also has support for eth signatures (interaction with dapps). App-specific addresses are used in this situation to protect privacy and to avoid accidental linking of off-chain credentials with the immutable on-chain activity.

For more details and/or extra questions, please refer to our support channel: https://uport.zendesk.com
